version: "3.9"

services:
  ngrok:
      image: ngrok/ngrok:alpine
      env_file:
      - ./.env
      command: 'http web:8000'        
      ports:
          - '4040:4040'
      expose:
          - '4040'

  web:
    build:
      context: .
      dockerfile: ./devops/backend/Dockerfile
    restart: unless-stopped
    entrypoint: /code/devops/backend/local-entrypoint.sh
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - static_volume:/code/backend/staticfiles
      - media_volume:/code/backend/media
      - .:/code
    depends_on:
      - db
      - redis

  
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      #      - ./mane_cafe-db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"

  redis:
    restart: unless-stopped
    image: redis:7.2.4
    ports:
      - "6379:6379"
    expose:
      - 6379

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "boburbekbotirov868@gmail.com"  
  #     PGADMIN_DEFAULT_PASSWORD: "supersecret"    
  #   ports:
  #     - "5050:80"  
  #   depends_on:
  #     - db  
  #   restart: unless-stopped
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  static_volume:
  media_volume:
  # pgadmin_data:
